# Generated by Django 3.1.1 on 2020-10-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('address_1', models.CharField(max_length=50)),
                ('address_2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('', 'Choose...'), ('MG', 'Minas Gerais'), ('SP', 'Sao Paulo'), ('RJ', 'Rio de Janeiro')], max_length=2)),
                ('zip_code', models.IntegerField(max_length=5)),
                ('check_me_out', models.BooleanField(default=False)),
            ],
        ),
    ]
