# Generated by Django 3.1.1 on 2020-10-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djax', '0002_auto_20201017_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=15),
        ),
    ]
