# Generated by Django 3.1.1 on 2020-10-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djax', '0003_auto_20201017_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='check_me_out',
        ),
    ]
