# Generated by Django 3.1.1 on 2020-10-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djax', '0004_remove_address_check_me_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='check_me_out',
            field=models.BooleanField(default=False),
        ),
    ]
