# Generated by Django 3.1.1 on 2020-10-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djax', '0005_address_check_me_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('', 'Choose...'), ('MG', 'Minas Gerais'), ('SP', 'Sao Paulo'), ('RJ', 'Rio de Janeiro')], default='SP', max_length=2),
        ),
    ]
